version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-docker
    ports:
      - 8080:80
    volumes:
        - ./app:/var/www/html
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: docker_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379